name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build Framework
      run: mvn -B install -DskipTests --no-transfer-progress -pl framework
    - name: Build Test Automation
      run: mvn -B install -DskipTests --no-transfer-progress -pl test-automation -am
    - name: Ensure browsers are installed
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      working-directory: test-automation
    - name: Run Tests
      run: mvn test
      working-directory: test-automation
