name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Maven dependencies
      run: mvn install -DskipTests
      working-directory: test-automation

    - name: Run TestNG tests
      run: mvn test -Dsurefire.suiteXmlFiles=testng.xml
      working-directory: test-automation


    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports
      

    - name: Upload Playwright trace
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-trace
        path: trace.zip

    - name: Generate Playwright report
      run: |
        npx playwright show-report
